### ISSUE TITLE
Server will not finish logging

### ISSUE THREAD

**Issue by asdf2345** [Tyrrrz/DiscordChatExporter#1009]
### Version

2.39.0

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

I'm trying to export an old sever with media, and it will not finish. I have no clue why it's only this server. Invite is aSbbXrT

I've been doing category by category, and it appears to get tripped up with the INFO category. The MUSIC/GAMING CHAT category also gives the same issue. GENERAL exported fine by itself. I haven't tried any other categories separately.

### Steps to reproduce

Join server
Open DiscordChatExporter
Paste token
Enter
Find server
Ctrl + A
Export with media

**Comment by SilSinn9801** [comment]
I am having this issue too, except it happens to me not only with one specific server (which appears to be a bit old & has too many channels to count) but also with some (but not all) direct message (DM) channels (regardless of age or total amount of messages). In my case the exports stop writing to disk after an arbitrary amount of KB. For a very-old DM channel with too many messages to count (it’s indeed my biggest private DM channel), the export always stops at 16 KB (only metadata, stylesheet, or incomplete SVG data, & no body text at all) no matter how many times I retry; for a newer DM channel with not that many messages, it’s stopping at 20 KB (meta, stylesheet, SVG, preamble, & only half of its very first message); & for a group DM channel that contains more messages than my biggest private DM (in spite of being more recent; last time I successfully exported such group DM using 2.39.0, it measured 16.1 MB & that happened almost 22 hours relative to this message), it’s now stopping at 1.76 MB. I said “some (but not all)” because there was one very recent private DM that I successfully exported today which only contained two messages I sent a few hours ago.
Also this HTML-export problem happens regardless of whether the files are being written to an uncompressed or compressed NTFS disk volume & regardless of whether they are being written fresh-new or overwriting files with the same filename(s).

It’s even possible this might be not a DCE bug but rather a problem with the Discord API itself (maybe it was updated again & it broke something again), considering that 22 hours ago I successfully exported all my updated DM channels just fine using the same 2.39.0.

**Comment by SilSinn9801** [comment]
OK, it seems that the “not finish logging” problem has just vanished, because now all my exports (of those DMs that were failing to export) are successful. It seems the problem was not a bug in 2.39.0 but rather a Discord API bug that was quietly fixed.

**Comment by asdf2345** [comment]
It appears to only happen in channels that have invalid invite links, I think. I got everything except announcements, affiliates, and anigame to export.

**Comment by Tyrrrz** [comment]
> It appears to only happen in channels that have invalid invite links, I think. I got everything except announcements, affiliates, and anigame to export.

Can you reproduce this consistently? Maybe by trying to export only that message?

**Comment by K4sum1** [comment]
Yes, consistently. Affiliates has literally 4 messages, two text, two invites, one invalid one valid.

**Comment by asdf2345** [comment]
Yes, consistently. Affiliates has literally 4 messages, two text, two invites, one invalid, one valid.

~~There were no other messages sent before this message~~

**Comment by asdf2345** [comment]
It apparently works now. Guess it really was a Discord issue.
