### ISSUE TITLE
Linked videos are not downloaded

### ISSUE THREAD

**Issue by C0nejin** [Tyrrrz/DiscordChatExporter#1012]
### Version

2.39

### Flavor

GUI (Graphical User Interface), CLI (Command-Line Interface)

### Details

I've been experiencing this bug for quite a while now with other versions as well (Both CLI and GUI versions). Whenever I try to export a Discord chat with its media, embedded videos from links are never downloaded, however, videos posted on the channel itself are downloaded just fine.
![image](https://user-images.githubusercontent.com/60204237/224108864-aa98b07e-c7fb-4832-b24a-4b013e9365a6.png)
![image](https://user-images.githubusercontent.com/60204237/224109020-3f70c023-be9b-4fb9-9f31-788fa2b13be3.png)

### Steps to reproduce

- Download any DiscordChatExporter version (CLI or GUI).
- Export, with the option to download media, a channel that has a linked video _(video example: https://cdn.discordapp.com/attachments/847572908011815012/1065410753852608643/i_am_currently_feeling_slight_displeasure_of_what_you_have_just_sent_lqrem.mp4)_.
- When you check the results, the linked video is not saved.

**Comment by Tyrrrz** [comment]
The issue is that you're exporting in JSON format, and JSON doesn't have special handling for image/video embeds, like HTML does. That means that links are just treated as links, not asset references, so the referenced files are not downloaded. That said, HTML export currently does not support plain video embeds, but it will in the next version. So if you want to be able to download those video files, the solution would be to upgrade to 2.39.1 when it's available and export in HTML.
