### ISSUE TITLE
Export to Json

### ISSUE THREAD

**Issue by tyzoid** [Tyrrrz/DiscordChatExporter#103]
Related to #102 

A json export would be very helpful for those who wish to preserve the data and formatting of the messages, yet still keep a compact, text-based, easily-parsable file type.

**Comment by benaryorg** [comment]
I tried parsing the CSV format using [*jq*](https://github.com/stedolan/jq) and some really ugly regex hackery, but I hit some problems with the contained unicode/multibyte characters.
Exporting as proper JSON would solve my problems to a very large extent, since that'd be ASCII only with escape codes for unicode (i.e. `\u0000` for the binary zero).

Until then I'll mess with my locale settings and hope to get everything working.…

**Comment by ealgase** [comment]
I think a big benefit of JSON output would be directly saving the message object, keeping all original data the way Discord returned it.

**Comment by Tyrrrz** [comment]
Merged JSON output to master.

Please check out the [latest CI build](https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/34271779) and report any errors you may find.
