### ISSUE TITLE
HTML Export are empty

### ISSUE THREAD

**Issue by MickaNoob** [Tyrrrz/DiscordChatExporter#1106]
### Version

2.40.0

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

Hey, i got a problem, 

When a export a channel, content of messages are empty.

Do you know why? 

![image](https://github.com/Tyrrrz/DiscordChatExporter/assets/20491694/0cd3a76f-dad9-44ca-a60d-7548c20e1026)

### Steps to reproduce

- Just export a Channel...

**Comment by CanePlayz** [comment]
make sure your bot has the message content intent enabled

**Comment by MickaNoob** [comment]
Ho thanks it's fixed.

**Comment by tcyrus** [comment]
I know the issue is closed, but can this be added to the Troubleshooting guide? I encountered the issue and couldn't find it in the guide.

It might be possible to check the `flags` in `/applications/@me` to make sure that `GATEWAY_MESSAGE_CONTENT` or `GATEWAY_MESSAGE_CONTENT_LIMITED` is there (e.g. `flags & ((1 << 19) | (1 << 18))`). Throwing a warning at the beginning might save people some time.

**Comment by Tyrrrz** [comment]
@tcyrus thanks a lot for that hint. I was looking for a way to check for the presence of that intent via the REST API and couldn't find it.

**Comment by CanePlayz** [comment]
> I know the issue is closed, but can this be added to the Troubleshooting guide? I encountered the issue and couldn't find it in the guide.

Has been added recently

**Comment by tcyrus** [comment]
Thanks. Just wanted to say a couple of things before dropping this topic.

This issue affects all export types. It's probably not worth renaming the issue since this case is now covered as part of the app as well as in the troubleshooting guide.

I'm not sure of the difference between `GATEWAY_MESSAGE_CONTENT` and `GATEWAY_MESSAGE_CONTENT_LIMITED`, which is why I suggested checking for both. The discord dev docs are unclear on how to validate this without hard coding the guild number threshold and comparing against that (this criteria might change).

Thanks for moving on this so quickly.
