### ISSUE TITLE
App is trying to save "Settings.dat" in c:\Windows\System32

### ISSUE THREAD

**Issue by Arthur-Freedom** [Tyrrrz/DiscordChatExporter#127]
why are you trying to access my systems.dat file in c:\windows folder ?

**Comment by RenanYudi** [comment]
Are you sure you're not talking about the 'Settings.dat' that stores GUI preferences? There isn't a Settings.dat in C:\Windows by default.

**Comment by Mascotte123** [comment]
![discordchatexporter_2018-12-23_23-32-15](https://user-images.githubusercontent.com/18115558/50388036-087daf00-070b-11e9-8e64-e65d5cb31050.png)

**Comment by RenanYudi** [comment]
Are you running the latest release (2.8)?

**Comment by Mascotte123** [comment]
yes

**Comment by Mascotte123** [comment]
![discordchatexporter_2018-12-23_23-34-53](https://user-images.githubusercontent.com/18115558/50388046-64e0ce80-070b-11e9-853d-b0b146062271.png)

**Comment by Tyrrrz** [comment]
Are you starting the app from `c:\Windows`? Is your working directory set to `c:\Windows` (via shortcut or something)?

**Comment by Mascotte123** [comment]
The folder "DiscordChatExplorer" is in my desktop.
This path c:\Windows\System32 is where it wants to write the html that I want to export I see 
don't know why ?

**Comment by Mascotte123** [comment]
what do you mean by "working directory" ?

**Comment by Tyrrrz** [comment]
Do you run the app by launching the `.exe` or maybe you have some `.lnk` shortcut?

**Comment by Mascotte123** [comment]
ok, thanks for quick help now i found a workaround
but it's a bug i think

when i open the app from the windows start menu:
![nvidia_share_2018-12-23_23-45-11](https://user-images.githubusercontent.com/18115558/50388103-00267380-070d-11e9-9106-77d6db443362.png)
, and i export a chat, it gives this error (see comment above)

but when i open the .exe from the DiscordChatExporter folder
![explorer_2018-12-23_23-47-24](https://user-images.githubusercontent.com/18115558/50388111-26e4aa00-070d-11e9-9a8c-5dfad0f37dad.png)
then it works


.. weird because the shortcut in the start menu redirects to that folder ...

**Comment by RenanYudi** [comment]
Can confirm. Same thing happens here.

**Comment by Tyrrrz** [comment]
Yeah, it's an undesirable behavior indeed. Surprised I never found it before.

**Comment by Tyrrrz** [comment]
Should be fixed upstream.
Can you check on this build? https://ci.appveyor.com/api/buildjobs/ltrq7nanyhhl37ja/artifacts/Deploy%2Fbin%2FDiscordChatExporter.zip

**Comment by Tyrrrz** [comment]
Fixed
