### ISSUE TITLE
Nicknames

### ISSUE THREAD

**Issue by now2blue** [Tyrrrz/DiscordChatExporter#153]
Thank you for this! Is it possible to show members nicknames on my server in the downloaded file instead of the users main name? It's a bit difficult sometimes to keep track of who is who.

Thank you

**Comment by Tyrrrz** [comment]
It is possible by querying all of the guild's members.
https://discordapp.com/developers/docs/resources/guild#guild-member-object

**Comment by now2blue** [comment]
I'm sorry, I am not a programmer or anywhere near it. If you could explain what I'm supposed to do with this info that would be very kind, but I understand if you don't.

Thanks

**Comment by Tyrrrz** [comment]
There's nothing you should do 😛 
I'm just saying it's possible to implement

**Comment by PortableTech** [comment]
I noticed too that the HTML output has both the username and nickname, but the CSV only has the username.  Would be nice to add another field to the CSV to list the Nickname as well since it seems we are already getting that data.

That said, awesome app, would love to see this functionality built into a bot that could export and email.  Great works!

**Comment by Tyrrrz** [comment]
I'm pretty sure HTML also doesn't have nicknames

**Comment by PortableTech** [comment]
> 
> 
> I'm pretty sure HTML also doesn't have nicknames

I was about to paste in some HTML output and then realized it shows the Username minus the #1234 on the end, but shows it if you hover over.  Yeah, getting the Nickname in there would be exceptionally helpful.

**Comment by rhockett94** [comment]
Is there any chance of this feature coming to the application? Please? I'd be very grateful.
