### ISSUE TITLE
Against developer terms of service?

### ISSUE THREAD

**Issue by DanTheMan827** [Tyrrrz/DiscordChatExporter#171]
https://discordapp.com/developers/docs/legal

2.4 End User Data. “End User Data” means all data associated with the content within the functionality enabled by the API or SDK, including but not limited to message content, message metadata, voice data and voice metadata. You acknowledge and agree that Discord and its end users, as applicable, retain all worldwide right, title and interest in and to the End User Data. If you have access to End User Data through the API or the SDK, you shall ensure that your Applications do not collect, use and/or disclose End User Data except (a) as necessary to exercise your rights under this Agreement, (b) in accordance with Discord’s Privacy Policy. If you have access to End User Data through the SDK, you additionally agree to get express permission from the End Users.

**Comment by Tyrrrz** [comment]
Hi,

1. DiscordChatExporter doesn't collect or disclose user data, it just presents it to you (the owner of said data) in a different, more accessible format.
2. If you are using a bot token to authenticate, it's not against TOS and is fully allowed. With a bot token you will be able to retrieve any messages that the bot has access to. You will obviously not be able to access your direct messages or any guild channels that the bot doesn't have access to.
3. If you are using a user token to authenticate, it's considered against TOS because user tokens are supposed to be used only within Discord itself. That said, using user tokens is the only way to retrieve direct messages, so for many people this is the only option they have.

To add on a little more, I think the reason Discord has a clause against self-bots is to prevent automating accounts for malicious purposes, e.g. advertisment, phishing, spamming. DiscordChatExporter only reads information and doesn't make any "write" actions so logically it shouldn't be a concern. Also, I don't know of any cases where users were banned for using DiscordChatExporter. I think with 64k+ users, it would've been reported by now.

With everything in mind, use this at your own risk and consider using bot token if possible.

**Comment by Tyrrrz** [comment]
Of related interest: https://news.ycombinator.com/item?id=25215415

**Comment by EpicLPer** [comment]
I wonder, have there been any official reports of people getting their accounts disabled after using the Exporter?

I'd love to export all my DMs. My account was disabled 3 weeks ago, and after battling with Support and messaging various Discord Staff got it reinstated again. Now I want to make a copy of all my DMs just to be safe, however the comment mentioned above from the Discord Developer leaves a somewhat bad taste...
