### ISSUE TITLE
DiscordChatExporter.Core as a NuGet package

### ISSUE THREAD

**Issue by mdiller** [Tyrrrz/DiscordChatExporter#173]
Have you considered providing `DiscordChatExporter.Core` as a nuget package? I'm working on a project for automating testing and documentation generation for my bot and it'd be helpful to be able to just interact with it via C# instead of using the cli.

**Comment by Tyrrrz** [comment]
I have, but it obviously adds a whole new layer of complexity since I'd need to be careful not to break something, whereas I can easily change stuff in Core now to fit the requirements of CLI/GUI. On top of that, I'd have to extract it to a different repository since it will have its own versioning and release cycle.
All in all it's possible, but I'd consider doing it only if there's a lot of benefit or if there are a lot of people who want this.

**Comment by mdiller** [comment]
Gotcha, that makes sense. Thanks for the explanation and for the great work!

**Comment by Tyrrrz** [comment]
Thank you :)

**Comment by Tyrrrz** [comment]
Closing this for now as there doesn't seem to be too much interest and I also prefer to keep `Core` internal for simplicity. :)

**Comment by matrumz** [comment]
I've been a long-time user of your Docker container to export my D&D session chats. I love it and thank you 🙇  

Long story short: I'm upgrading our experience with a Discord Bot so I can run exports right in the app (then feed those to a self-hosted LLM that users will be able to chat with via the bot).

I would've loved a nuget package of this project to jumpstart my work, but I completely understand not making the package if there's not a lot of community interest.

Consider this a long-winded +1 on the feature request! ❤️
