### ISSUE TITLE
Error when exporting larger channels (HttpErrorStatusCodeException: Error HTTP status code: ServiceUnavailable)

### ISSUE THREAD

**Issue by develoByte** [Tyrrrz/DiscordChatExporter#200]
![image](https://user-images.githubusercontent.com/34870321/62392819-0d6ed080-b52e-11e9-9ae6-fb4f73528012.png)
This happens often if I try to export a larger channel.

**Comment by Tyrrrz** [comment]
This is weird that this happens. 5XX means there were some server-side issue and DiscordChatExporter even has retry for it. It could be that the export process performs denial of service but I heavily doubt that's possible.

**Comment by prrjn** [comment]
I have the exact same error while retrieving channels with 20k - 40k+ messages.
I have an error everytime with this kind of queries but had more chances with limiting the software to a day or two worth of data. Anything more than that is automatically a "SERVICE UNAVAILABLE" and with smaller queries it's 50-50. Sometimes it doesn't works and sometimes it does. @Tyrrrz

**Comment by BlueMarshalx** [comment]
I think a dummy solution to the export of channels with too many messages is to split it using different date periods then just merge them or name them appropriately. Just inconvenient but doable.

**Comment by Tyrrrz** [comment]
Looks like if it were the case of making too many requests, Discord should've responded with 429: https://discordapp.com/developers/docs/topics/rate-limits#more-precise-rate-limit-resets.

So it seems that it's an issue on their side. If there's a hidden limit, we need to try to figure out if there's a pattern. Adding arbitrary delays for a chance of avoiding this issue seems like a bad idea.

**Comment by endlord2024** [comment]
I also encountered it several times. It's pretty annoying when it appears around 90%. The maximum limit that i tested is 30-35k messages twice a day (Average filesize with plain text is 6.0Mb, Max 6.8Mb).

My idea is that, what if we simply decrease the message count the program can download one time? 
For example choosing not only the date, but the time as well. I think it's pretty easy to implement, because you can choose the date already.

Or save the time when it was terminated, then when you launch next, offer you to continue where you left it. 

I dont know wich one is the easier to implement, but if none, please can you do that to write a try catch when the service is ended, and then save those messages he already scanned?

**Comment by Tyrrrz** [comment]
You can set the time range already in CLI and sorta in GUI as well (#36).

This issue will be affected by #177 because the data extraction will be interleaved with writing output to file. Since the exporter will be streaming, the output file will contain messages up until the export fails, instead of nothing.

Unfortunately, Discord doesn't send back any rate-limiting related info in its responses so it's hard to determine when it's hit or when it's about to be.

**Comment by Tyrrrz** [comment]
Please try the new version

**Comment by Tyrrrz** [comment]
Is it still reproducible?

**Comment by CatTheHacker** [comment]
Works with latest version.
