### ISSUE TITLE
Export embed content in csv

### ISSUE THREAD

**Issue by JonathanMM** [Tyrrrz/DiscordChatExporter#225]
Hello,
firstly, many thanks for your tool, it's very helpful for me! But, I think it can be better :)
On a discord server, I have a dedicated channel for a bot, which post embed content. When I export this channel in CSV, well, the file is almost empty, only the date and the name of the bot are added, not the embed content. It should be nice if this content is exported.
To do this, I suggest to have a column per field (the name of the column should be the title of the field). For me, it allows to analyse the data.

**Comment by Tyrrrz** [comment]
Hi.

Embeds can have any set of fields, or even no fields at all, so it's hard to render them in CSV. Maybe JSON export (#103) is a better solution due do its more dynamic but still parsable nature.

Looking back, I should've probably added JSON instead of CSV from the beginning, although message formats were a lot simpler back then.

**Comment by Tyrrrz** [comment]
Closing this for now as I don't think CSV will ever support embeds at all (PlainText only supports it partially). It's better to focus efforts on #103 instead.
