### ISSUE TITLE
Run as service

### ISSUE THREAD

**Issue by Murkur** [Tyrrrz/DiscordChatExporter#239]
Option to run this exporter as a service on a windows or linux machine and auto update a the html file as new messages are posted

**Comment by 161134050** [comment]
I don't think this program would be suitable for this - it would have to keep hitting the messages endpoint for each channel, as it doesn't connect to the websocket

**Comment by Murkur** [comment]
was more think logging one chat as an option as i would like to index a servers chat and have it auto update to my webserver

**Comment by Tyrrrz** [comment]
Thanks for your interest in this. Continuous exporting and automation scenarios are out of scope for this project. Its primary use case is for making "snapshots" rather than maintaining a synced offline version of the channel.

You can take a look at scheduling setup on wiki, maybe that will handle your use case https://github.com/Tyrrrz/DiscordChatExporter/wiki

**Comment by Murkur** [comment]
oh didnt know about scheduling, can you set it up to it uses one file and will update over the same file?
also is there an option to make most recent messages first while oldest are last?

**Comment by Tyrrrz** [comment]
No to both questions. Your best bet is to overwrite the same file or set sliding date ranges, e.g.

- Base export: beginning of time -> now
- Export 1: date of base export -> now
- Export 2: date of export1 -> now

and so on

**Comment by Murkur** [comment]
okie thanks
