### ISSUE TITLE
Linux Mint 2.16 GUI run issue

### ISSUE THREAD

**Issue by beskhu3epnm** [Tyrrrz/DiscordChatExporter#248]
I'm having trouble running Discord Chat Exporter on Linux Mint since updating from 2.15 to 2.16.
`WINEPREFIX="$HOME/wine" WINEARCH=win32 wine DiscordChatExporter.exe
0012:fixme:wer:WerSetFlags (2) stub!
0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
wine: Bad EXE format for Z:\home\user\Desktop\DiscordChatExporter\DiscordChatExporter.exe.
`

**Comment by Tyrrrz** [comment]
The GUI version on Linux/Mac is not supported unfortunately. Looks like the wine hack stopped working after switching to .NET Core.

**Comment by beskhu3epnm** [comment]
Thank you. I have an additional question:

I don't understand why total message count was removed.
> [HTML/TXT] Removed message count from the metadata. Due to the fact that the messages are exported as they are streamed, total number of messages is not known ahead of time.
I found this a very interesting and sometimes useful feature. Is it possible to add it back in?

**Comment by Tyrrrz** [comment]
Previously, DiscordChatExporter would pre-load all messages in memory before rendering them to file. Because of that, there were issues when exporting very large channels: #125 #88 #228 #174 #206 #177.

Since 2.16, DiscordChatExporter now renders messages as it loads them, so it doesn't know how many messages there are in total (this info is not available in API). It won't be possible to render message count in the beginning like before, but it could be possible to add it to the end of the file.

**Comment by Tyrrrz** [comment]
If you really need message count and you're okay with it being at the bottom instead of at the top, please create a new issue for that.

**Comment by beskhu3epnm** [comment]
Well, I now understand why you omitted it, but that really sucks. I liked that little feature a lot. If you can retroactively add it to the top after the document has been fully downloaded, that would be ideal. Otherwise, adding it to the bottom would be good.

**Comment by Tyrrrz** [comment]
Unfortunately adding it to the top is not easy as then I'd have to make sure leave enough space for it first, then re-open the file stream at the end, look for the correct tag and insert message count. It's not impossible of course but for such a little feature I don't think doing that is worth it.

Adding it to the end of the file, on the other hand, isn't hard. Created #249 for you, closing this one.
