### ISSUE TITLE
Saving in Database file

### ISSUE THREAD

**Issue by billyon** [Tyrrrz/DiscordChatExporter#257]
A more practical way to save messages instead of html or json would be with database format so that the new messages can be added to the old ones instead of remaking the messages files and losing information.

**Comment by archiif** [comment]
Yes, seconding this. Having a way to update your exported file instead of recreating them each time would be very useful! Maybe try sqlite3.

**Comment by makeworld-the-better-one** [comment]
Since there is already CSV output, it shouldn't be too hard to make a script that converts that into an sqlite database.

**Comment by Tyrrrz** [comment]
While I understand the use case, adding support for more formats makes the project much harder to maintain. There's most likely not going to be any more formats added past this point.

As an alternative, it would most likely be possible to add a feature to the CLI version that would print the output to stdout instead of a file. That way, you can run the CLI programmatically, read the output in streaming way, and then relay that to the database. If that would work for you, let me know in a comment and I'll create a separate issue.
