### ISSUE TITLE
Export all channels from all guilds in a single action

### ISSUE THREAD

**Issue by MeatPony** [Tyrrrz/DiscordChatExporter#274]
Could you make a feature that allows people to export all channels, in servers, and dms, as a way to archive all chats locally?

**Comment by Tyrrrz** [comment]
Hi
You can multiselect channels. Is that what you're asking?

**Comment by MeatPony** [comment]
I mean like a button that just exports everything

**Comment by Tyrrrz** [comment]
As in, all channels from all guilds?

**Comment by MeatPony** [comment]
Yeah, there is no option to export all server, or multiple servers at once, which is kinda slow.

**Comment by PeterPorker3** [comment]
How close is this to being implemented? I'm looking for a project and may be able to help if it's an issue with not enough time to do it. I am also investigating a solution to archiving my discord conversations, all this software needs is this and the ability to download attachments and pictures.

**Comment by Tyrrrz** [comment]
I think this issue is unrelated to what you're asking about. #21

**Comment by wyattscarpenter** [comment]
Here is a workaround script that does this. Unfortunately, it is a bash script meant to be run on windows due to my personal set up, but if you remove the .exe suffixes it should work on linux. I couldn't do this in windows scripting because it has to finesse the output of `guilds` before handing it back to `exportguild`, and I don't know how to do that in cmd.

```
./DiscordChatExporter.Cli.exe exportdm -o "dump/dms" -t "$1"
./DiscordChatExporter.Cli.exe guilds -t "$1" | while read line || [[ -n $line ]]; do echo "$line"; ./DiscordChatExporter.Cli.exe exportguild -g "${line%% *}" -o "dump/${line%% *}" -t "$1"; done
```
(this is also available in one of my git repos, here: https://github.com/wyattscarpenter/util/blob/master/export-all-discord)

I expect this should be a pretty easy feature to add to the main program, but it's been a while since I did anything with C#, so I can't help there.
