### ISSUE TITLE
FTP upload

### ISSUE THREAD

**Issue by ALEEF02** [Tyrrrz/DiscordChatExporter#329]
Hi!
I'm trying to use DCE on a very large server (5 years, 5000+ members). Is there a way I can use DCE in its current state to back up the chat logs to an FTP server? If not, is that a possible feature that could be added?
Thanks!

**Comment by ALEEF02** [comment]
I'm currently looking into C# FTP uploading. I'll attempt to make a PR, but it's been a little since I've worked with C#
![image](https://user-images.githubusercontent.com/12904259/87977239-47105280-ca83-11ea-8731-6e9c7c183bae.png)

**Comment by Tyrrrz** [comment]
Hi.
No, this is not possible and is not a planned feature. There are too many different usage scenarios to try accommodate all of them.
Your best bet is to make a local export and then transfer it afterwards. You will want to split it into smaller parts, either by dates or by using partition limit, because 5 years of messages will crash whatever program you will try to open them in.
