### ISSUE TITLE
Could not execute because the specified command or file was not found

### ISSUE THREAD

**Issue by rTphoenix** [Tyrrrz/DiscordChatExporter#334]
Sorry, I saw someone else had the problem on mac but they got it resolved themself.
I keep getting this message, I've copied what was to be typed out and I've done it manually, but it doesn't seem to change, I keep getting this.

 Could not execute because the specified command or file was not found.
 Possible reasons for this include:
   * You misspelled a built-in dotnet command.
   * You intended to execute a .NET Core program, but dotnet-DiscordChatExporter.Cli.dll does not exist.
   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

Most of the time, I type this in terminal:
 dotnet DiscordChatExporter.Cli.dll export -t {token from application tab} -c {ID of the DM i want to export}

Could it be my macos version? I'm only on Sierra.

**Comment by Tyrrrz** [comment]
Are you in the same directory as the dll file?

**Comment by reverseTeebz** [comment]
> Are you in the same directory as the dll file?

I'm not quite sure, taking another look I'm not sure if I even used the right file, I'm not exactly sure where else it could be though

**Comment by Tyrrrz** [comment]
There are macOS usage instructions you can follow:

https://github.com/Tyrrrz/DiscordChatExporter/wiki/macOS-usage-instructions
https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#using-the-cli-

**Comment by reverseTeebz** [comment]
what's the path of the directory?

**Comment by Yudi** [comment]
dotnet-DiscordChatExporter.Cli.dll really doesn’t exist
dotnet DiscordChatExporter.Cli.dll does 
If it still doesn’t work
Try `echo $PATH` and paste the content here for us.

**Comment by Yudi** [comment]
It’s the `cd` command. “Change Directory”.
To check which directory you are currently in, run `pwd`

**Comment by 1Eskor** [comment]
i am in dotnet path; /usr/local/share/dotnet .. 
.NET 5.0 SDK (v5.0.401) installed and .NET Core 3.1 Runtime (v3.1.19) installed,
when i run dotnet DiscordChatExporter.Cli.dll export -t 'token' -c 000054053100032060

i get 
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-DiscordChatExporter.Cli.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
  
  any help appreciated
