### ISSUE TITLE
[GUI] More specific export time limits

### ISSUE THREAD

**Issue by Xyrexus** [Tyrrrz/DiscordChatExporter#36]
First off I'd just like to thank you for the program, it's really nice, but I was wondering if it would be possible to have the option for a tighter export window? At the moment you can only limit it by day, would it be possible to add a day and time option?

**Comment by Tyrrrz** [comment]
Hi, thank you. What's the use case for this?

**Comment by Xyrexus** [comment]
A friend and I have idea brainstorming sessions for things we write together, so being able to save logs with a tighter timeframe would be pretty useful.

**Comment by Mirrorshadez** [comment]
I'd like to request the this enhancement as well.
Specific use case is that I want to export for a 24 hour period each days chat.  But my time zone and the timezone of the Discord and the chat don't map to the default 12:00 start and end time used by default.

**Comment by Tyrrrz** [comment]
This is still not possible to do in GUI due to the fact that the date/time choose we have doesn't support precise time selection.
However, when using CLI you can specify date ranges down to milliseconds if you want. Is that good enough or you need it in GUI?

**Comment by AmazingPenis1** [comment]
I would also appreciate that. Or at least a better tutorial for windows on how to use the command line.

**Comment by RenanYudi** [comment]
CLI is pretty easy. Just run it on cmd with `-h` to see the instructions. 
For an example, if you want to export messages sent after September 15th 11:15 PM:
```
DiscordChatExporter.Cli.exe export -t tokenhere -c channelIDHere --after "15-SEP-2019 11:15 PM"
```

![Screen Shot 2019-09-16 at 19 08 51](https://user-images.githubusercontent.com/12040397/64997997-d3c50f80-d8b8-11e9-93af-3c6ae797bc73.png)

**Comment by DAOWAce** [comment]
I'm here after trying to do this again and not finding a way in-program (GUI) to work reliably.

I half use this tool to save chatlogs because I'm an archiver at heart and don't want to lose my history, and half use it to show other people chatlogs instead of expending a huge amount of time and effort copy/pasting text or taking tons of screenshots.  There's no real solution for Discord's chat system that doesn't have major issues attached with it.. besides this program.

It seemed to half work when I put "2PM" in the first date selection, but it only worked in the initial input, so I ended up just manually editing a full daily export.

However, when testing again while writing this comment, it does actually seem to work.  I typed "2PM" after the first selection and "6:50PM" after the second selection (with a space), and even though the text disappeared when confirming the date, the program respected the settings and exported the selected time range.

That's, a bit baffling.  Was something changed since the time this issue was opened?

**Comment by Tyrrrz** [comment]
@DAOWAce a lot of this have changed in a year of course 😂 
The date pickers come from [Material Design toolkit](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit) and it might be possible that they've changed something regarding this.
