### ISSUE TITLE
Skip already downloaded files

### ISSUE THREAD

**Issue by rygos** [Tyrrrz/DiscordChatExporter#382]
Hello,

if I create a export with --media all the images are in a subfolder of this export. if I run an export some days later every image gets downloaded again with (0) or later (1) on the filename. is it possible to skip already downloaded files?

regards,

rygos

**Comment by Tyrrrz** [comment]
This is potentially dangerous as the images may share the same name and be different. For example, when attaching an image with no name, you will get `unknown.png` as the name and it will be the same for all such images.

**Comment by rygos** [comment]
Okay. But what if you use the attachment id for filename?

**Comment by Tyrrrz** [comment]
It used to work like that previously, but then people said they wanted readable file names that match what they uploaded. Can't please everyone.

**Comment by rygos** [comment]
Sorry, I didn't know that it was like this before.

Too bad. I might then put something together for my archive myself.
Should such a wish arise again, maybe add another param

--media (load files with original filenames)
- media-with-ids (save files with id)

**Comment by andrewkolos** [comment]
Hey. I just want to summarize this and make sure I understand correctly. Right now (2.23), attachments are downloaded and the downloaded files are given the names of the attachment (e.g. if I upload `Bagel.png` to a channel and export it, the picture of the bagel will show up in the folder as a file named `Bagel.png`). When file name collisions are encountered (either because someone uploaded their own `Bagel.png` or we do another export later, the program doesn't look for a way to see if the existing media is the same as the one we are about to download so it can skip downloading it. Does this sound right?

I imagine that each discord attachment has some form of UID. If we could save this information when we download media, we could use it during future exports to save time/bandwidth and skip downloading the media that already exists. We could append this UID onto the end of filenames, or we could save a separate cache file that maps filenames to UIDs and save it in the same folder as we do the attachments. Any thoughts?

**Comment by Tyrrrz** [comment]
> Hey. I just want to summarize this and make sure I understand correctly. Right now (2.23), attachments are downloaded and the downloaded files are given the names of the attachment (e.g. if I upload Bagel.png to a channel and export it, the picture of the bagel will show up in the folder as a file named Bagel.png). When file name collisions are encountered (either because someone uploaded their own Bagel.png or we do another export later, the program doesn't look for a way to see if the existing media is the same as the one we are about to download so it can skip downloading it. Does this sound right?

That's correct.

> I imagine that each discord attachment has some form of UID. If we could save this information when we download media, we could use it during future exports to save time/bandwidth and skip downloading the media that already exists. We could append this UID onto the end of filenames, or we could save a separate cache file that maps filenames to UIDs and save it in the same folder as we do the attachments. Any thoughts?

Attachments do have an ID, so maybe doing something like this is an option: `mydog-1234-567-890-1234.png` (previously only the ID was used). However, that option also exports other files which are not attachments, which might not all have IDs.

A cache file in the media directory could be a solution, but I'd prefer to keep things as simple as possible.

**Comment by rygos** [comment]
Okay. Because i Need something like this (too many Images on my server) i write something on my own.

Thank you for your replys.

:)
