### ISSUE TITLE
Where does the output go from DiscordChatExporter.Cli.exe exportall -t token?

### ISSUE THREAD

**Issue by drnow1** [Tyrrrz/DiscordChatExporter#406]
I ran **DiscordChatExporter.Cli.exe exportall -t token**

I don't see any file generated in the current directory. What is the filename generated?
Is it possible to add a feature that says "Writing to file XXX.html" so I know where to find the output?
What happens if I kill the process now with ctrl+c ? Will the file be there?

**Comment by Yudi** [comment]
The files will be exported to the current directory unless otherwise changed with the `-o` option.<br/>You can check your current directory by running `echo %CD%` in cmd or with `pwd` in Powershell or Mac/Linux.<br/><br/>

Yes, the files will be saved if the process is killed. <br/>But keep in mind that, depending on the chosen format, killing the process can corrupt the file that was being exported at the time.

**Comment by Yudi** [comment]
The files will be exported to the current directory unless otherwise changed with the `-o` option. Using this option might help you.<br/>You can double-check your current directory by running `echo %CD%` in cmd or with `pwd` in Powershell or Mac/Linux.<br/><br/>

The files won't appear if you kill the process, because they should already exist.

**Comment by drnow1** [comment]
I didnt use -o
I don't see any files in the current directory. What is the name of the file generated?

**Comment by Yudi** [comment]
The name format for DMs is:
```
Direct Messages - Private - User [DM ID]
```
<br>
For server channels:

```
Server name - Category - Channel name [Channel ID]
```

**Comment by drnow1** [comment]
I ran the command:
C:\util\cli>DiscordChatExporter.Cli.exe exportall -t [token]
3 hours ago. It's still running.
I don't see any files generated in current directory. I searched entire drive for *Messages* but haven't found any. Is this a bug? It looks like no files have been generated?

**Comment by Yudi** [comment]
Try running the command again for a few minutes but with the `-o C:\path\to\another\folder` option to see if it helps

**Comment by drnow1** [comment]
I ran this command but no files are generated:
C:\util\cli>DiscordChatExporter.Cli.exe exportall -t [TOKEN] -o c:\util\
Is there a -v option to display more info on what's going on?

**Comment by Tyrrrz** [comment]
The files would probably be in `C:\util\cli>`. The program should report its progress, so even if it's running for 3 hours, you should know how far in it is.

**Comment by Tyrrrz** [comment]
Alternatively, try to export a single channel and see if this works.

**Comment by drnow1** [comment]
C:\util\cli>DiscordChatExporter.Cli.exe exportdm -t [TOKEN]
I don't see any output on the screen and no files are generated! Is there a -verbose option to show me what DiscordChatExporter is doing?

**Comment by drnow1** [comment]
The GUI also doesn't work:
![gui](https://user-images.githubusercontent.com/72711922/95691992-7d2c2100-0bf1-11eb-8868-44dcdcddb462.png)

**Comment by Tyrrrz** [comment]
Guess it doesn't work for some reason ¯\\\_(ツ)\_/¯

**Comment by drnow1** [comment]
Does it generate a logfile saying what is going on with error message?

**Comment by Tyrrrz** [comment]
No, it doesn't.
