### ISSUE TITLE
Error occurred ']' invalid without a matching open

### ISSUE THREAD

**Issue by QuantumRange** [Tyrrrz/DiscordChatExporter#413]
![grafik](https://user-images.githubusercontent.com/49843948/96398349-f4524e00-11cb-11eb-88df-62df0edc5de4.png)

Why I think this happened:
![grafik](https://user-images.githubusercontent.com/49843948/96398545-6b87e200-11cc-11eb-895f-0e53d9a5a0d3.png)

( No, the harddisk is not only full with DC requests, it is only about 1GB.
But I had moved a few files at the same time and apparently there was not much space. )

But what I would say about the previous bug, it would be nice if there were some user friendly bugs, so for example it just pauses instead of crashing.

**Comment by Tyrrrz** [comment]
It's prooooobably not because of the lack of disk space, but having only 12 KB free will definitely cause some issues. Especially if you're exporting to that same drive.

**Comment by QuantumRange** [comment]
The error happened to me again and I had the one on the other hard disk where I export ~90GB free.

**Comment by MMK21Hub** [comment]
Can confirm. I have plenty of space on my D drive (where DiscordChatExporter is installed).
![image](https://user-images.githubusercontent.com/50421330/104424949-f4b67700-5577-11eb-9931-7157b68c7ad1.png)

**Comment by Tyrrrz** [comment]
Does it happen consistently @MMK21Hub ?

**Comment by MMK21Hub** [comment]
It used to work fine, but recently I've been getting this error at the end of every job.

**Comment by Tyrrrz** [comment]
Can you see if it's a specific message (type of message, content, or something else) that triggers this error? Basically something to help reproduce this error.

**Comment by efindus** [comment]
It happened to me. It propably has something to do with attachments deleted from discord servers. In my case download was stopping at specific message with exe file (which turned out to be a virus (keylogger), and I am unable to download it now), after deleting the message with the file, export finished without problems.

**Comment by Nan0Scho1ar** [comment]
This message in particular breaks the Json export for me. Once I deleted the message the export works fine.
![image](https://user-images.githubusercontent.com/2265764/105480819-f3ace480-5cf1-11eb-81fd-f93603a34340.png)

**Comment by Tyrrrz** [comment]
Nothing about that message looks immediately suspicious to me.
To be able to debug this properly I will need access to the channel with the message that causes this error. So if anyone gets this again and doesn't mind sharing an invite link (my Discord is `Tyrrrz#5447`), let me know.

**Comment by justoboy** [comment]
I ran into this error with 2 different servers last night. #general in this server: [Rickles Safe Space](https://discord.gg/ricklevr) as well as #general in this server: [Raspberry Pie](https://discord.gg/fDTrSDR2).
Here is what it was able to download from those channels before it crashed.
[error_channel_messages.zip](https://github.com/Tyrrrz/DiscordChatExporter/files/5860695/error_channel_messages.zip)

**Comment by justoboy** [comment]
After looking into it myself it seems that in both cases the message directly after the last one in the files contains a mention of someone not in the server. The message in the Sentdex server has **<@76572365732653726547623>** and the one in Rickles server has **<@!159398981431>**.

**Comment by kelvinwop** [comment]
@Tyrrrz https://discord.gg/you-zitsu messages in pallet-cafe cause this too

**Comment by kelvinwop** [comment]
yea broken pings look like the cause

**Comment by kelvinwop** [comment]
This problem only exists in the release, if you run the latest code it doesn't have this issue.

**Comment by 96-LB** [comment]
I vaguely remember getting an error like this while testing  #479. If I recall correctly, the JSON export threw this exception while the rest specified that an invalid snowflake was the cause. If they are indeed the same error, that would explain why the latest CI build no longer has this issue.

**Comment by Tyrrrz** [comment]
@96-LB interestingly enough, this issue was created long before the snowflakes were introduced, which means it was probably caused by something else. I'll make a new release, let's see if someone else reports this issue in the future.

**Comment by 96-LB** [comment]
@Tyrrrz Hmm, I'll try to check it out and see if I can reproduce it on a few different versions.

**Comment by 96-LB** [comment]
I've done some debugging to try to isolate the problem. I can confirm that once snowflakes were introduced, this error could indeed be caused by invalid mentions. The overarching cause seems to be an exception occuring in the second line of this method in `MessageExporter.cs`:
```cs
public async ValueTask ExportMessageAsync(Message message)
{
    var writer = await GetWriterAsync();
    await writer.WriteMessageAsync(message); // the code continues after an exception here 
    _messageCount++;
}
```
I'm not entirely familiar with how C#'s async operations handle exceptions, but the code appears to continue even if the awaited method throws, only bubbling up later once everything has completed. In the case of a JSON export, the postamble tends to fail validation when writing the end of the `messages` array because an entire content block is missing from the export. In other exports, the original exception crashes the program at a later time.

This specific cause has been fixed, as invalid mentions no longer throw exceptions, but my guess is that this JSON error just blanketly covers up other internal errors. I don't know what the original cause of this issue was, but I'd imagine that exporting it with a different format would reveal it. It seems that all of the comments on this thread except the OP's seem to relate to the invalid mention issue, so it's possible that the OP's cause has been patched sometime in the past four months.

**Comment by Tyrrrz** [comment]
@96-LB 

Thanks for looking into this!

> I'm not entirely familiar with how C#'s async operations handle exceptions, but the code appears to continue even if the awaited method throws, only bubbling up later once everything has completed.

Hmm, this is definitely not how it _should_ work, so this very weird. Maybe it's an issue with `ValueTask`?
I assume the original exception (related to invalid mention, not the uneven ']' that bubbles up later) is triggered here:
https://github.com/Tyrrrz/DiscordChatExporter/blob/f22b048d32ccbc4708dc63ffd6112a35f73cb2fb/DiscordChatExporter.Domain/Exporting/Writers/JsonMessageWriter.cs#L224
It should definitely bubble up immediately and stop further execution.

I'll try to repro it again. I will need to revert to the commit prior to your fix and try exporting a channel that has an outdated mention, correct?

> This specific cause has been fixed, as invalid mentions no longer throw exceptions, but my guess is that this JSON error just blanketly covers up other internal errors. I don't know what the original cause of this issue was, but I'd imagine that exporting it with a different format would reveal it. It seems that all of the comments on this thread except the OP's seem to relate to the invalid mention issue, so it's possible that the OP's cause has been patched sometime in the past four months.

It is very likely that's the case. We should really try to find out why the original error is replaced with another, because this is not good.

**Comment by 96-LB** [comment]
@Tyrrrz 
> Hmm, this is definitely not how it should work, so this very weird. Maybe it's an issue with ValueTask?

I actually misunderstood what was happening; I think the exception bubbled correctly, and all the writers were disposed before the program crashed. Since the postamble is written when a message writer calls `DisposeAsync()` and then `ResetWriterAsync()`, a second exception is thrown during the disposal of a JSON writer. This seems to be what's covering up the underlying exception.

> I assume the original exception (related to invalid mention, not the uneven ']' that bubbles up later) is triggered here:
> https://github.com/Tyrrrz/DiscordChatExporter/blob/f22b048d32ccbc4708dc63ffd6112a35f73cb2fb/DiscordChatExporter.Domain/Exporting/Writers/JsonMessageWriter.cs#L224

Yes, the error was thrown there because of the markdown visitor failing to handle bad mention nodes.

> I'll try to repro it again. I will need to revert to the commit prior to your fix and try exporting a channel that has an outdated mention, correct?

Also correct. I've been testing on the v26.0 release.

---

I think everything just boils down to an exception being thrown here in `MessageExporter.cs`:
```cs
private async ValueTask ResetWriterAsync()
{
    if (_writer != null)
    {
        await _writer.WritePostambleAsync(); //specifically this line
        await _writer.DisposeAsync();
        _writer = null;
    }
}
```
I'm not really sure if any of the other exporters could potentially raise an error when being disposed, but the JSON one seems to perform some validation that could certainly mask a future issue. A potential quick solution could be to add a parameter to skip the postamble and use it when disposing?

**Comment by Tyrrrz** [comment]
I see, that makes sense.
Maybe it's worth using the `SkipValidation` option in [`JsonWriterOptions`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonwriteroptions?view=net-5.0) to disable validation so that the original exception is thrown instead? I can't think of a better solution.

**Comment by 96-LB** [comment]
The only problem I can see with that is making it a lot easier to accidentally output invalid JSON and a lot harder to debug. Though, I'd imagine it's unlikely that the JSON export gets any breaking changes at this point, and we can always debug it with validation turned back on if someone points out an issue in the export format.

**Comment by Tyrrrz** [comment]
Yeah, it's a downside, but hiding the exception seems more dangerous. At a later point we can write tests to validate the structure of output JSON.

**Comment by 96-LB** [comment]
Agreed. I've opened a pull request to make the tweak.
