### ISSUE TITLE
Unknown channels crash exporter

### ISSUE THREAD

**Issue by Heath123** [Tyrrrz/DiscordChatExporter#474]
In Discord unknown channels appear like this:
![image](https://user-images.githubusercontent.com/13787163/104056530-8de83500-51e8-11eb-8d66-001ed03a5d66.png)
Howerver they crash this exporter with an error about an unknown snowflake (will try to get more info and PR a fix)

**Comment by 96-LB** [comment]
The exporter has no issue with id's coming from unknown channels coming from different servers:
![image](https://user-images.githubusercontent.com/21089343/104106076-e0753000-5280-11eb-87cf-2a4f5b676300.png)
However, I was able to recreate your bug with the channel mention `<#1>`. I dug around in the code and found that snowflake parsing throws an error if the string is not 15 digits long. It shouldn't be an issue to handle that exception and print #deleted-channel/user/role when it occurs.

The error handling should probably take place in `HtmlMarkdownVisitor.cs` and `PlainTextMarkdownVisitor.cs` (found in `DiscordChatExporter.Domain/Exporting/Writers/MarkdownVisitors`), since that's the portion of the code that currently checks whether the snowflake matches to any channel/user/role. If you'd like to make a PR, go for it!

**Comment by rikai** [comment]
Is there any way to get a new binary release that contains this fix?

**Comment by Tyrrrz** [comment]
@rikai you can download the CI build for now:
https://github.com/Tyrrrz/DiscordChatExporter#download

**Comment by rikai** [comment]
> @rikai you can download the CI build for now:
> https://github.com/Tyrrrz/DiscordChatExporter#download

Perfect, thanks. I was able to get everything working!
