### ISSUE TITLE
Add option to ignore large servers with exportall command

### ISSUE THREAD

**Issue by Exr0n** [Tyrrrz/DiscordChatExporter#480]
Howdy,

This tool has been extremely useful, thank you all for making it!
However, I find that when I want to blanket export all my DMs and personal servers, I would like to ignore public servers with long message history. It would be super useful to have an `--ignore-larger-than=1000` members option.

I'm not too familiar with C#, but I have other programming experience. I'd be happy to try and implement this and make a PR if someone can give me some pointers (where to start, roughly what needs to be changed, what should I watch out for?)

**Comment by andrewkolos** [comment]
You could add your new arg to the `exportall` command by adding it to `ExportAllCommand.cs`. Something like

```cs
        [CommandOption("ignore-servers-larger-than",
            Description = "Excludes servers with more members than the given number.")]
        public int? ExcludeServersLargerThan { get; set; }
```

Then in the `ExportAsync` method below, you would add another `if`-guarded continue [here](https://github.com/Tyrrrz/DiscordChatExporter/blob/915f4c8d9f62704d3d5795b3f0f8c79cf5990366/DiscordChatExporter.Cli/Commands/ExportAllCommand.cs#L26).

The hardest thing is that, right now, DCE does not pull the approximate number of users in a guild (server) from Discord. The call to the Discord API is found in `DiscordClient.GetUserGuildsAsync`. According to the [official API reference](https://discord.com/developers/docs/resources/guild#guild-object), if the `with_counts` query param is set to to `true`, the API will include a `approximate_member_count` field in its response, so you could use that. You would need then to modify `Guild.Parse` to parse this field and save it to a new property in `Guild`. Then, back in `ExportAllCommand.ExportAsync`, you could read this property to tell how many users (approximately) a sever has.

I wrote this pretty hastily, so feel free to ask for clarification.

**Comment by Exr0n** [comment]
Thanks for the overview! This is a little embarrassing, but I don't actually know how to build or test the application. I've installed `dotnet-sdk` but running `dotnet build` in the root of the project get this error:

```
error MSB4236: The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found.
/usr/share/dotnet/sdk/3.1.108/Roslyn/Microsoft.CSharp.Core.targets(59,5): error : Failed to create CoreCLR, HRESULT: 0x8007000E
```

It seems like an env variable is messed up? Are you able to give me some pointers?

**Comment by andrewkolos** [comment]
Hmm. I use Visual Studio on Windows, and the normal build function works out-of-the-box. I am assuming you are running on Linux, where I wouldn't know any more than you unfortunately. I wonder if @Tyrrrz might know what to do here.

**Comment by Tyrrrz** [comment]
@Exr0n you need the windows desktop dotnet sdk on top of the regular sdk, if you want to work on the GUI. Otherwise, you can just run `dotnet build` inside `DiscordChatExporter.Cli` and it will only build the CLI project.

Regarding the original request, I'm wary of adding things like that. Filters need to be composable somehow, otherwise we will eventually end up with `--ignore-larger-than`, `--ignore-images`, `--ignore-bots` and so on, which is maintenance nightmare.

**Comment by andrewkolos** [comment]
@Tyrrrz though I have a hunch that making such a system would most likely not worth the trouble, do you have any ideas for what a "composable" filtering system might potentially look like? I am trying to get a better idea of what you mean by this. Do you mean something like some sort of DSL for filtering? I'm guessing not, because that seems just as heavy-handed and hard to maintain (though I have no experience with such things). Just curious.

Or, perhaps you mean having something like `IExportFilter` and each CLI option adds another instance of `IExportFilter` to `ExportRequest` (which can accept an arbitrary amount of filters), which would allow us to have many such filters without downstream code (like `ExportRequest`'s constructor/properties) having to implement all this logic all in one big messy ball.

**Comment by Tyrrrz** [comment]
> though I have a hunch that making such a system would most likely not worth the trouble, do you have any ideas for what a "composable" filtering system might potentially look like?

Essentially, it would need to incorporate a query language that the user would be able to use to filter content dynamically. Something like this:

`--filter "Context.Guild.Members.Count < 100"`

It would then have to support various operators like `and`/`or` as well.

Also, reading the OP again, it seems like the issue here is that they want to ignore channels with long message history. The number of members in a guild (which we don't retrieve by the way) has no correlation with that. Of course, we also can't get the number of actual messages in the channel because Discord doesn't provide it and we can only know that ourselves once the export has already finished.

**Comment by andrewkolos** [comment]
> Also, reading the OP again, it seems like the issue here is that they want to ignore channels with long message history. The number of members in a guild (which we don't retrieve by the way) has no correlation with that.

That's a great insight.

As an aside, if you ever feel you get a lot of requests for new filter options, I wouldn't mind taking a crack at building your proposed query language idea. It could be a fun learning experience.

**Comment by Exr0n** [comment]
> Also, reading the OP again, it seems like the issue here is that they want to ignore channels with long message history. The number of members in a guild (which we don't retrieve by the way) has no correlation with that.
Just to add some nuance, I want to ignore channels that I don't care about, which (in general) means public servers. For example, I have a server with some close friends whose message history goes back five years, but I still want to export that. 

> Of course, we also can't get the number of actual messages in the channel because Discord doesn't provide it and we can only know that ourselves once the export has already finished.
After some more thought, there may be a way to approximate this. In the Discord app, you can search for the first message in a channel, and comparing the dates might be a good heuristic. However, that sounds like a (or many) complex API calls, so I figure the members heuristic may be better for my particular use case.

> As an aside, if you ever feel you get a lot of requests for new filter options, I wouldn't mind taking a crack at building your proposed query language idea. It could be a fun learning experience.
I have a little experience with parsing expressions algorithmically.. I can try to help out if needed (but again, I don't know C#)

Thank you all for the attention to this (possibly niche) request!

**Comment by Tyrrrz** [comment]
Another option would also be to make the core DiscordChatExporter public so others can write their own custom programs that fit these very specific use cases.
