### ISSUE TITLE
Wrong leading zero user discriminator in JSON

### ISSUE THREAD

**Issue by squidass** [Tyrrrz/DiscordChatExporter#500]
When using JSON as an export format, in mentions of users, if user has leading zeros in discriminator (zeros before the first nonzero digit) these discriminators are being written without these zeros which results in incorrect discriminator.

**Comment by ConnorKrammer** [comment]
I can't test this and don't have time to submit a proper pull request (I'm not at my usual setup) but I'm pretty sure the cause is [this line](https://github.com/Tyrrrz/DiscordChatExporter/blob/3aef7faa1ee47f2c4977782fd6f8db7c39a1d0c0/DiscordChatExporter.Core/Exporting/Writers/JsonMessageWriter.cs#L172):
```C#
_writer.WriteNumber("discriminator", mentionedUser.Discriminator);
```
Compare to [another line](https://github.com/Tyrrrz/DiscordChatExporter/blob/3aef7faa1ee47f2c4977782fd6f8db7c39a1d0c0/DiscordChatExporter.Core/Exporting/Writers/JsonMessageWriter.cs#L231) that writes out `mentionedUser.Discriminator`:
```C#
_writer.WriteString("discriminator", $"{message.Author.Discriminator:0000}");
```

The code around both of these lines is nearly the same and appears to serve the same purpose, so I might suggest making it into a function to avoid discrepancy creeping in (like just now). Note that after the latter line the author's avatarUrl [is written out](https://github.com/Tyrrrz/DiscordChatExporter/blob/3aef7faa1ee47f2c4977782fd6f8db7c39a1d0c0/DiscordChatExporter.Core/Exporting/Writers/JsonMessageWriter.cs#L233), but this is not the case for the code around the former line; I'm not sure if this is deliberate or a similar discrepancy as the discriminator handling.

Hope this helps.

**Comment by 96-LB** [comment]
Yeah, this appears to be the problem. I would believe the lack of avatarUrl in the former case is intentional, since mentions don't actually expose the avatar in any of the export formats. It interests me that the nickname isn't written out in the latter line though, since the HTML output displays user's nicknames above each of their messages.

**Comment by Tyrrrz** [comment]
Yeah, the discriminator discrepancy needs to be fixed, the lack of nickname in message author is unintentional I think (can't think of any reason why it's missing), but lack of avatar in mention is intentional (like @96-LB said, it's not really relevant there).
