### ISSUE TITLE
Is there any way to export a guild while excluding channels?

### ISSUE THREAD

**Issue by l1ving** [Tyrrrz/DiscordChatExporter#504]
My guild has roughly 75 channels, but a couple of them are join log / message logging channels which I would like to exclude. I understand that I can export individual channels at a time, but it feels very hacky to have a bash script like

```bash
#!/bin/bash

discord-chat-exporter-cli export --channel 000000000000000000 -o /some/path --bot
discord-chat-exporter-cli export --channel 000000000000000001 -o /some/path --bot
discord-chat-exporter-cli export --channel 000000000000000002 -o /some/path --bot
discord-chat-exporter-cli export --channel 000000000000000003 -o /some/path --bot
# Continue for another 70 channels
```

If there isn't a way to exclude specific channels with a flag, I'd like to make this a suggestion instead.

**Comment by Tyrrrz** [comment]
Why does it feel hacky though? This approach offers composability, while having options like exclude/include etc. will always be limited and clunky.

Also, you can probably declare an array of channel IDs and iterate them in a loop, to simplify your script.

**Comment by l1ving** [comment]
Eh I mean I only want to exclude 1 or 2 channels, instead of copy and pasting the same command 70 times into a bash script. 

Sure, I could use an array with all my channel IDs but it's still more tedious than a `--skip-channels some_id`

**Comment by 96-LB** [comment]
If this is regular, a simple workaround could be to remove the bot's read permission from the channels you don't want exported. If for some reason you'd want that channel in the future, you can temporarily give the bot access again.

**Comment by l1ving** [comment]
I mean that's absolutely right, but bash isn't meant for more complex things. I could totally do that but it's like using safety scissors on a steak.

**Comment by 96-LB** [comment]
I've used Python in the past for automating DiscordChatExporter -- it works on exactly the same principle. But if your use case is simple enough, I think altering the bot's permissions is the best way to handle a quick skip.

Personally, I wouldn't be opposed to a `--skip-channels` flag for `exportdm`, `exportguild`, and `exportall`, since it's probably a common enough scenario to want to avoid exporting a particularly sensitive or large channel. I don't know what would be the preferred way to support inputting a list of ID's though (are there any existing flags which accept multiple values as reference?).

**Comment by l1ving** [comment]
I looked at a couple existing issues and `--some-flag arg_one arg_two arg_three` is the syntax

**Comment by Tyrrrz** [comment]
> Eh I mean I only want to exclude 1 or 2 channels, instead of copy and pasting the same command 70 times into a bash script.
> 
> Sure, I could use an array with all my channel IDs but it's still more tedious than a `--skip-channels some_id`

Why not use the `guild` command to get the list of servers, parse the IDs into an array with `grep`, and then exclude the two channels you want excluded?

**Comment by l1ving** [comment]
> I mean that's absolutely right, but bash isn't meant for more complex things. I could totally do that but it's like using safety scissors on a steak.

That's what I said here, while I could write a command to do this it isn't intuitive to new users and it's still more tedious than a built in flag to do it.

I'd make a pull to do this myself but I don't know C#, unfortunately.

I understand if it isn't worth your time adding, I just think it would be much easier than having each person parse the channels to exclude something on their own.

**Comment by Tyrrrz** [comment]
It's not about being worth adding, it's about being worth maintaining. There are many similar requests coming every once in a while, each asking for slightly different option to fit their specific use case.

CLIs in general are not the simplest tools to use. They are, however, perfect for automation. In order to ensure that the tool can be reasonably automated, the operations it provides need to be modular and composable (much like functions in a programming language). Yes, that comes at the cost of making some higher level concerns more difficult to implement, but in my opinion the modularity and simplicity are more important in this scenario.

Also, you don't have to use bash or powershell to work with it. You can use Go or whichever language you are most comfortable with.

The task really comes down to:

1. Execute `channels`
2. Split the lines from stdout and extract channel IDs
3. Feed the IDs into `export` command

One thing I can see that could be improved is allowing `export` to take multiple IDs at a time to make use of parallelization, because currently it's limited to just one.

Another point is that we don't have a GUI for Linux/macOS which would make things like these much simpler. CLI is not a replacement for GUI, it's more of a lower level but advanced alternative. I imagine having an x-platform GUI would solve this issue, but unfortunately the UI framework we're using is not portable. We could migrate from WPF to [Avalonia](https://avaloniaui.net/) in the future tho.
