### ISSUE TITLE
Is there a way to not export emojis

### ISSUE THREAD

**Issue by Zinc-OS** [Tyrrrz/DiscordChatExporter#516]
He i'd like to know if there is an option for not exporting emojis(or other weird text. I'd prefer just ASCII, really) to plain text documents.

If not, that would be a really great feature.

**Comment by Tyrrrz** [comment]
No there is not. Assuming you mean the unicode emojis and not custom emojis, there is no other way to represent them anyway, so the only other option is to just omit them, which is not feasible since there is no good way to accurately identify all emojis in text. In any case, this is likely out of scope of the project.

**Comment by Zinc-OS** [comment]
Thats fine
