### ISSUE TITLE
Whitespace options on HTML Exporter?

### ISSUE THREAD

**Issue by Psiah-ence** [Tyrrrz/DiscordChatExporter#517]
So... the problem I've had with Discord, and what I was hoping this would solve, is that I don't seem to have an easy, automatic way to export or copy and paste chat logs from Discord to other applications--such as Google Docs or Kanka.io--and be able to preserve both the white space _and_ basic formatting options like _italics_ or **bold**. Every method I've tried, I've had to manually fix one or the other, and for the community I'm trying to manage, this is far too much work to do manually. Unfortunately, this exporter does not end up solving that problem for me.

Playing around with it, I found that the big issue comes down to the html exporter using a sort of "preserve whitespace" style to, well, preserve whitespace, and the programs I'm trying to copy into want to drop that like it's hot. Even tried a quick find/replace to get rid of the "class" attribute that ended up orphaned when the style got dropped, and replacing it with a "style" right on the tag itself to replicate the effect. Nope, programs dropped that too. Also, there isn't a good way to just find-replace all the line breaks with html tags automatically, because it creates _way_ too many new lines with the formatting.

With that in mind, I tried other options. HTML seems like it's the only one that's going to preserve the italics / bold type formatting, but I did notice that the .json programatically replaces newlines with a /n, so it seems like, potentially, most of the work for what I'm looking for is already done.

Would it be possible to create an option for, or a version of, the html exporters that takes a more active role in handling whitespace? Because if so it would _really_ help me out with what I'm trying to do. :)

**Comment by Tyrrrz** [comment]
I don't understand what you mean by "more active role in handling whitespace"? Replace newlines with `<br>` and spaces with `&nbsp`? That won't work with, for example, preformatted code blocks, which is why the preserve whitespace is used (and also why it's used in the Discord app itself). HTML is not meant for consumption by other programs, so sounds like either you're using the wrong tool for the job and should be using JSON, or the problem is with the programs you're using not being able to handle whitespace correctly.
