### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by PrivateServersGANG** [Tyrrrz/DiscordChatExporter#528]
Need help building it add me on discord if u can help please Unnamed#0152

**Comment by 96-LB** [comment]
If you're just looking to run the program, you should be able to download builds from the links [here](https://github.com/Tyrrrz/DiscordChatExporter#download).

**Comment by Tyrrrz** [comment]
If you want to build, download & install .NET SDK v5.0 and (for now) .NET SDK v3.1.

**Comment by FeXd** [comment]
I came here for this question as well, because I [needed a feature](https://github.com/Tyrrrz/DiscordChatExporter/pull/524) that had been merged recently, and I'm not super familiar with .NET or Docker.

Pulled form the [Dockerfile](https://github.com/Tyrrrz/DiscordChatExporter/blob/master/Dockerfile), you can run:

`dotnet publish DiscordChatExporter.Cli -o DiscordChatExporter.Cli/publish -c Release`

to build the CLI at least.

**Comment by Tyrrrz** [comment]
@FeXd you can also download the artifacts from the latest CI build: https://github.com/Tyrrrz/DiscordChatExporter#download
CI builds are ran on every commit.

**Comment by Tyrrrz** [comment]
Added this: https://github.com/Tyrrrz/DiscordChatExporter/blob/master/Contributing.md#building-the-project-locally

**Comment by FeXd** [comment]
Awesome, thank you @Tyrrrz ! ❤️
