### ISSUE TITLE
Access Forbidden in GUI but fine in CLI

### ISSUE THREAD

**Issue by BLANK-TH** [Tyrrrz/DiscordChatExporter#550]
Occasionally, if you try to download a channel in the GUI, it'll say access denied however it works fine in CLI.
I suspect this to be caused when you don't have access to the category of the channel but do have access to an individual channel (however I haven't thoroughly tested this and can't be sure). It seems to work fine in the CLI however and exports just fine. Also worth noting that if you export it in the CLI, the category will be named `Missing` which likely correlates with the previous theory.

**Comment by 96-LB** [comment]
I wasn't able to reproduce this. Are you able to provide an example set of permissions that results in this behaviour?

**Comment by BLANK-TH** [comment]
Sure, the permissions on the channel and category when this happened was the following:
Channel:
Denied: `@everyone` (read and send permissions)
Allowed: A bunch of roles I didn't have, role that I had (has read permissions but not send)
Category:
Denied: `@everyone` (all permissions)
Allowed: Roles I didn't have

Permissions not mentioned were just set to the default (usually `/`)

**Comment by 96-LB** [comment]
I tried to replicate your permission setup but didn't encounter the bug. Here are my permissions:

![image](https://user-images.githubusercontent.com/21089343/117341149-c71b7380-ae6f-11eb-93e3-1c014776e5d9.png)
* `RESTRICTED` denies every permission to `@everyone`
* `#test-2` denies every permission to `@everyone`
* `#test-2` enables "View Channel" and "Read Message History" for the role `@test`

I gave `@test` to a bot and used its token to export both the CLI and GUI with no issues. Two tangentially related things I did find, however, were 1. that keeping "Read Message History" denied results in the exporter finding no messages in the given time period (which makes sense) and 2. that the GUI actually has no problem getting the category name despite the CLI reporting `<unknown category>` (which makes less sense).

I imagine that you used v2.26.1 when you opened this issue as the latest version wasn't released yet and because your restricted category was exported as `Missing` rather than `<unknown category>`. My guess is that it was fixed with the last update - could you try the same channel with the latest version of the GUI to see if it works now?

**Comment by BLANK-TH** [comment]
Very late reply but it works now, I still have no idea what caused it but it works.
