### ISSUE TITLE
Watch YouTube videos inside the HTML files

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#570]
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

I have no idea if this is even possible, so this is partly a suggestion and partly a question if this is possible. As the title says, it's about watching YouTube videos directly in the HTML file just as you can in Discord itself:

![image](https://user-images.githubusercontent.com/81419612/117993869-63e28300-b340-11eb-9fd3-2aab50216994.png)

**Comment by quentinmay** [comment]
Found a solution using html's [iframe](https://www.w3schools.com/html/html_youtube.asp). Just need to replace the typical youtube link "/watch?v=" with "/embed/" and instead of showing the video description, make it show the video iframe embed instead. Unfortunately this solution wouldn't really work with shortened or different youtube URLs. Good enough for most situations tho.
Result Screenshot
![image](https://user-images.githubusercontent.com/73214439/122029140-7d348000-cd81-11eb-9237-e1c14f9ee6da.png)
