### ISSUE TITLE
Consider mentioning `choco` as a download option

### ISSUE THREAD

**Issue by FarisHijazi** [Tyrrrz/DiscordChatExporter#629]
### Details

The windows unofficial package manager [`choco`](https://chocolatey.org/) already supports downloading from the release page of github.

```sh
choco install -y DiscordChatExporter
# then run it from the command line
DiscordChatExporter
```

I personally used choco to download DiscordChatExporter, at the time of writing, it downloaded version `2.11`

Hope you add this in the README.md even if it's just experimental, might get more users onboard.

**Comment by Tyrrrz** [comment]
I maintained the choco package initially, but it became progressively more annoying with their review process, so seeing as the downloads from choco were abysmal I decided to drop it. That said, the version it currently downloads (2.11) had built-in auto-update functionality, so it should update to latest separately from choco anyway. I'm hesitant to add it to readme though because I'm not planning to maintain the package. I wonder if I could assign someone else from the community as a maintainer?

**Comment by FarisHijazi** [comment]
hmmmmm

in that case, let's resolve this issue as "won't fix" until further notice, I'll look into choco packages, but no promises

**Comment by Smart123s** [comment]
Hi, I'd be happy to maintain the choco package.
I currently maintain 25 chocolatey packages with over 45.000 downloads in total.

My choco profile: https://community.chocolatey.org/profiles/Smart123s
Package sources: https://github.com/Smart123s/chocolatey-packages

If you would like to discuss it further, contact me via chocolatey, or leave a comment here. To let me push updates to the package, you have to add me as a maintainer of the **chocolatey** package.
