### ISSUE TITLE
Date format should not influence dates in the bottom line of embed messages

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#648]
### Export format

HTML

### Details

Currently, the date format the user chooses also changes the date format used in the bottom line of embed messages which it shouldn't do. So for example, if that's the original bottom line in Discord:
![image](https://user-images.githubusercontent.com/81419612/125692101-3c03f5c1-55a0-4588-bc8b-7b4e268bc2f6.png)

With my preset it changes to the following in the HTML file:
![image](https://user-images.githubusercontent.com/81419612/125692184-ae6d5cab-737b-411b-8fbf-43488504a272.png)

**Comment by Tyrrrz** [comment]
Why do you think it shouldn't influence those dates?

**Comment by CanePlayz** [comment]
Because if you change the language setting in Discord, it changes the date format of the timestamps but has no influence on the dates in those embeds besides translating things like "yesterday," but the format itself stays the same.

**Comment by CanePlayz** [comment]
Because if you change the language setting in Discord, it changes the date format of the timestamps but has no influence on the dates in those embeds.

**Comment by Tyrrrz** [comment]
I've decided to leave this as it is now because I believe it ultimately provides better user experience. All dates should really be localized and it seems more like a bug than anything that Discord doesn't do it.

Note that we're not parsing the date out of a free text field. The value shown in the footer is always returned by Discord as a date.

**Comment by CanePlayz** [comment]
Ok
