### ISSUE TITLE
Option to ignore nicknames and use usernames

### ISSUE THREAD

**Issue by CanePlayz** [Tyrrrz/DiscordChatExporter#653]
### Export format

HTML

### Details

I know that you can already see someone's username in a tooltip by hovering over their nickname in the HTML file, but I think it would be great if there was an option to fully ignore those nicknames and instead use the usernames in the exported chats. I'd use the usernames because, on our servers, nicknames can quickly change and become a bit confusing. Also, if you really want to conserve chats for a lifetime, I think it's better if you have proper usernames that you always will remember instead of having dynamic and changing nicknames.

**Comment by Tyrrrz** [comment]
> I think it's better if you have proper usernames that you always will remember instead of having dynamic and changing nicknames.

I believe even usernames can be changed, so the only static identifier is the user ID, which is also inserted in HTML: https://github.com/Tyrrrz/DiscordChatExporter/blob/e00f126a5e39bcfed6f8fc405690d8b29b343676/DiscordChatExporter.Core/Exporting/Writers/Html/MessageGroupTemplate.cshtml#L172

I'm going to mark this out of scope because of the project's status and the low community interest in this issue.
