### ISSUE TITLE
Long file paths crash the export process

### ISSUE THREAD

**Issue by DannyDorito24** [Tyrrrz/DiscordChatExporter#708]
### Version

version 2.30.1

### Flavor

CLI (Command Line Interface)

### Details

When attempting to export a channel that contains media or links to media that are too long for the OS to handle, the export process hangs, then crashes. Maybe something could be added where if a filename is too long for the OS it truncates it to a certain length.

### Steps to reproduce

send a message in a channel such that it will embed an image with an extremely long filename, too long for your OS to handle
Export the channel with that message, and you will get "System.IO.PathTooLongException."

**Comment by 96-LB** [comment]
This is an OS limitation and varies by device. There's nothing really that can always be done to solve the problem. What if the export is run in a location that only allots 5 characters for media files? After using up a.png, b.png, etc., the exporter would run into trouble; meanwhile anything ending in `.jpeg` wouldn't even get a filename. Normally the exporter uses a hash to differentiate, but obviously in this case there's no room to insert one.

I'd imagine it's way too complicated to handle this exception in every case, but I do see how very long media filenames could be problematic and stop a channel from ever being exported. Maybe there could be a setting to limit the maximum length of included media files? That could at least stop a pathological (pun unintended) filename.

**Comment by Tyrrrz** [comment]
> Maybe there could be a setting to limit the maximum length of included media files? That could at least stop a pathological (pun unintended) filename.

Currently we already truncate file names of downloaded media:

https://github.com/Tyrrrz/DiscordChatExporter/blob/ea31b1b270bfe77fdca6ad6eb5aecf98ae1b0780/DiscordChatExporter.Core/Exporting/MediaDownloader.cs#L112

(assuming that's what you meant)

**Comment by 96-LB** [comment]
Ah, yeah that is what I meant. 42 seems fairly reasonable, as you'd still need to be pretty deep in a filesystem to hit the 256-character path limit for Windows (I'm not familiar with the limit on other OS's though).

**Comment by Tyrrrz** [comment]
I'm generally averse to automatically truncating paths based on OS max path length, because:

1. That would make the file names non-deterministic and unpredictable. Frankly, it leads to poor user experience if you run an export in one directory, get one set of file names, then run it another, and get another set. This is especially bad if the user specifically sets the output file path or template.

2. That would break portability with "reuse media" option. Imagine running an export in a directory with a really long name and getting truncated file names. Then you copy the exported files to a directory with a short name and run the export again with "reuse media". Because the file path limitations are different, all of the cached files will be missed.

Ultimately, I believe throwing the exception is the best solution. If you don't nest your exports too deeply, it should be fine.

Also, if you are on Windows 10+, you can enable long file path support and forget about this issue forever:

https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by 96-LB** [comment]
@Tyrrrz Oooh, I wasn't aware of the long filepath support!

...after opening the link and following the directions, I've found it already enabled. Guess I did it in the past and forgot entirely about the feature 😅
