### ISSUE TITLE
Support animated emojis

### ISSUE THREAD

**Issue by Delphox** [Tyrrrz/DiscordChatExporter#71]
Right now animated emojis [show as code](https://lithi.io/file/e574.png) on messages, and show as their static PNG version on reactions.

**Comment by Tyrrrz** [comment]
Discord has animated emojis? Is this new?

**Comment by TVdata** [comment]
It was added on december.

**Comment by Delphox** [comment]
Yup, it was added [in late december](https://blog.discordapp.com/21-12-2017-change-log-76e8c0331266) as another Nitro perk (alongside higher quality screensharing). They have their own 50 emoji limit separated from regular emojis in any server and can be uploaded by non-Nitro users, although only subscribers can use them.

**Comment by alexandre433** [comment]
To save storage it could be added as a link to that exact png/gif/animated thing.
For example this gif - https://cdn-images-1.medium.com/max/1600/1*0Po1GUmpfQGIXyxbdvUDnA.gif
Instead of the gif beeing stored, the link itself could be stored instead, and/or added to an .html to display that gif/image/even maybe video.

Because everything we add onto the discord server it will go to the discord's main server, BUT if the discord server you're trying to get the animated image/video/gif from is deleted I have no idea if the link still works, but I don't believe it will.

**Comment by CanePlayz** [comment]
I wanted to open an issue about this and stumbled upon this. So why exactly was this closed?

**Comment by Tyrrrz** [comment]
Because it was implemented.

**Comment by CanePlayz** [comment]
Oh sorry, I just had to let the HTML file load longer for the emoji to start moving, my bad 🤦‍♂️
