### ISSUE TITLE
Add message filter: "reacted with specific emoji"

### ISSUE THREAD

**Issue by antonionardella** [Tyrrrz/DiscordChatExporter#715]
### Details

Use case:
- A user posts a question to Discord which could be added as useful content to a documentation or wiki page
- A developer adds a ✍️ reaction (or a custom server emoji to the message called :wen_docs: and emoji ID 893851165022908416)
- DCE extracts all messages with the reaction which have the defined emoji 
- Developer has now the list of all messages and can add those to a todo task list to extend, correct the software documentation/wiki page

CLI usage:
`--filter "reaction:✍️`
`--filter "reaction:wen_docs`
`--filter "reaction:893851165022908416`

**Comment by thebigsmileXD** [comment]
I wanted to request the same feature. I have been using the 📌 reaction with a custom JS script in the browser version of discord, which sent the message to a text tile. It does not work on mobile/desktop client for obvious reasons though, so DCE sounds like a viable option. It would also be great to grab all replies to a message with a specific reaction as well (or to include x messages before/after the reaction) in order to have better "context"
