### ISSUE TITLE
Export all discord

### ISSUE THREAD

**Issue by Sunkwii** [Tyrrrz/DiscordChatExporter#744]
### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

Add a function to export all discord at once with estimated time if possible and in different files per discord.

**Comment by 96-LB** [comment]
You can select multiple channels by holding shift and clicking on channels to multi-select. Estimated time is unfortunately not very feasible because every channel varies. If you want to organize or name the files in a specific way, you can employ a sort of hackish trick to use [filename templates](https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#generating-the-filename-and-output-directory-dynamically) on the GUI. More info on that last point [here](https://github.com/Tyrrrz/DiscordChatExporter/issues/676#issuecomment-894836554).

**Comment by Sunkwii** [comment]
Can I select multiple servers at once?

**Comment by 96-LB** [comment]
I don't think there's away to do that yet on the GUI. It's possible on the CLI, however.

**Comment by Sunkwii** [comment]
Ah ok, I can't seem to use this version. No problem

**Comment by 96-LB** [comment]
Try checking out the [wiki](https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#using-the-cli) for instructions on how to use the CLI. Might solve any problems you have running it. You can also join the Discord if you still need help.

**Comment by Sunkwii** [comment]
I am doing this command but I have an error that the token is invalid, I am trying to log in with a token from a discord bot.

dotnet DiscordChatExporter.Cli.dll exportall token -t

**Comment by 96-LB** [comment]
`-t` should come before the token, and you'll also need to put `-b` in there so that DiscordChatExporter knows you're using a bot token.

**Comment by Sunkwii** [comment]
it works perfectly, thank you
