### ISSUE TITLE
Linux usage instructions

### ISSUE THREAD

**Issue by mitchtbaum** [Tyrrrz/DiscordChatExporter#75]
How do I use this on Linux?

**Comment by Atagait** [comment]
If you install [Mono](https://www.mono-project.com/download/stable/#download-lin) you can run the CLI version just fine. I have yet to see if the GUI version works.

**Comment by RenanYudi** [comment]
You can with CLI and Mono. It isn't that user friendly, but it works.

---
**Installing Mono**
To get mono on Ubuntu/Debian ([other distros and more info here](https://www.mono-project.com/download/stable/#download-lin-ubuntu)): 
Open Terminal and type
1. `sudo apt-get install mono-devel`

You can check if mono was installed successfully using `mono -V`, it should output its version. If it didn't work, try the link above for more info.

---

**Downloading and using DiscordChatExporter**

1. Download the latest DiscordChatExporter CLI release [here](https://github.com/Tyrrrz/DiscordChatExporter/releases/latest) and extract its contents on your Desktop to a folder called `DiscordChatExporter`.

2. Open terminal and type to change Terminal directory:
`cd ~/Desktop/DiscordChatExporter`

3. Replace `TOKEN` and `CHANNEL`, and execute the command to run DiscordChatExporter.Cli.exe:
`mono DiscordChatExporter.Cli.exe -t TOKEN -c CHANNEL`
---
It's also possible to run the CLI on macOS, but installing mono is a little bit different, since you'd be using brew or macports instead of apt. I have a simple terminal script for the CLI on macOS here if @Tyrrrz wants to take a look.

The GUI might work with Wine or Wineskin, but I'm not sure, since I haven't tried it.

**Comment by RenanYudi** [comment]
Oh lol, sorry. I just finished writing this, didn't see your reply, Atagait.

**Comment by RenanYudi** [comment]
I wasn't able to run the GUI with Mono, nor with a fresh installation of Wine on both Ubuntu and macOS.
Mono outputs: 

> The entry point method could not be loaded due to Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. assembly:PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:<unknown type> member:(null) signature:<none>

Wine on Ubuntu gives me [this](https://pastebin.com/kc3aZW4M)
And a more or less configured Wineskin on macOS still gives me this even after applying some fixes I've found on the internet:
![screen shot 2018-08-03 at 00 40 40](https://user-images.githubusercontent.com/12040397/43623129-f993a2bc-96b5-11e8-8eee-947882c01d11.png)

**Comment by RenanYudi** [comment]
Yeah... No way I could make the GUI work.

Should we include this instructions on somewhere more visible, @Tyrrrz? I had the same question when I first saw this tool on Reddit.
The instructions would be too large for the Readme, so maybe a Wiki page? Then we could include Mac and Linux instructions, and also the "workaround" way to get the token.

**Comment by Tyrrrz** [comment]
I'm on vacation currently but I'll look into it later

**Comment by strafe** [comment]
Until the documentation is up you'll also probably want to define a different output format using the `-f, --format` parameter. Ex:
```bash
mono DiscordChatExporter.Cli.exe -t <token> -c <channel> -f PlainText
```
<hr>

Is there any hope for the CLI to be .NET Core compatible?

**Comment by Tyrrrz** [comment]
There is currently only one dependency, I believe, that forces CLI to be on .NET fx. I will look into moving it to .NET core when I have time.

**Comment by Tyrrrz** [comment]
I've created a wiki page meanwhile, thanks @RenanYudi!
https://github.com/Tyrrrz/DiscordChatExporter/wiki/Linux-usage-instructions

**Comment by Kentoseth** [comment]
I tried running this on Ubuntu 18.04 and got the following error:

```
Unhandled Exception:
System.MissingMethodException: Method 'System.Net.Logging.get_Http' not found.
  at System.Net.Http.HttpMessageInvoker.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00027] in <27bbdd4ceaf04a95b172ee502d76a725>:0 
  at System.Net.Http.HttpClient.SendAsync (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x0007a] in <27bbdd4ceaf04a95b172ee502d76a725>:0 
  at System.Net.Http.HttpClient.SendAsync (System.Net.Http.HttpRequestMessage request) [0x00008] in <27bbdd4ceaf04a95b172ee502d76a725>:0
... (lots of other content)
```

Does anybody have a fix for this?

**Comment by RenanYudi** [comment]
Well that’s weird… It worked fine for me on a fresh 18.04 install without needing to edit anything. 

I’m also working on a more detailed wiki page, I’ll include the full instructions there and open an “Issue” once it’s done so Tyrrrz can replace the current wiki.

**Comment by jman005** [comment]
Hey, I've got the GUI version running fine with Wine (give or take some cosmetic issues), mind if I add the instructions to the wiki page?

**Comment by Jefferderp** [comment]
This looks really useful! Just FYI, the app (or at least the CLI) is cross-platform thanks to `mono`.

**Comment by RenanYudi** [comment]
It works and it's great :-)! You can add a GUI section [here](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Linux-usage-instructions) after Tyrrrz's approval. 

The `winehq-staging` and `development` branches aren't working on 18.04, though. They have libfaudio0 as a dependency, but apt is not installing it. Stable is working.

And you forgot `wine` in the last command.

**Comment by Tyrrrz** [comment]
Add it to wiki :)

**Comment by jman005** [comment]
Added, thanks.
