### ISSUE TITLE
Mimic human usage pattern

### ISSUE THREAD

**Issue by Panabou** [Tyrrrz/DiscordChatExporter#777]
### Details

Hello, after reading all the information, I am a bit worried that my account might get deactivated after using this tool.
How can Discord detect the usage? Is there the need to  transmit a client name? Or do they automatically evaluate the usage pattern (e.g.,  fast and large, uninterrupted downloads)? If so, could you please implement a random delay option that mimics a human usage pattern? Thank you!

**Comment by Tyrrrz** [comment]
This project is not operating in bad faith so there's no reason to implement ways to "avoid detection". Besides, a few random delays won't confuse anyone. Attempts to mimic human usage would put us in a race that we can't reasonably win.

If you are that concerned about breaking TOS, use a bot account. Or create a throwaway user account that you don't care about. Otherwise, you'll have to deal with the risks.

Related: #171
