### ISSUE TITLE
Flexible output generator based on JSON export

### ISSUE THREAD

**Issue by anomaly33k** [Tyrrrz/DiscordChatExporter#793]
### Flavor

CLI (Command Line Interface)

### Export format

HTML

### Details

I have noticed several related issues [743](https://github.com/Tyrrrz/DiscordChatExporter/issues/743), [345](https://github.com/Tyrrrz/DiscordChatExporter/issues/345), [265](https://github.com/Tyrrrz/DiscordChatExporter/issues/265), and [262](https://github.com/Tyrrrz/DiscordChatExporter/issues/262) - they are all regarding different output formats.

I have two use cases:

1. Archiving content for automated analysis
2. Archiving content for viewing by humans

I started off exporting channels only as JSON, and I tried to parse that output into an HTML file similar to the HtmlLight output, but it required significant work to achieve that. I ended up giving in and re-exporting as HTML, meaning there was gigabytes of duplicate data.

It would be more efficient if there was a feature (or other app) to render a JSON export using the existing HTML templates, or any other custom template. So only one set of message data would need to be stored (JSON), and it could easily be displayed in any format (HTML, Plain text, etc).

The logic around message grouping and referencing previous messages, and even images is not important to me -- just basic display of text chat with timestamps within the existing HTML style would be sufficient.

There may be existing 3rd party tools which could achieve this - some instructions on the wiki would really help.

**Comment by Tyrrrz** [comment]
> It would be more efficient if there was a feature (or other app) to render a JSON export using the existing HTML templates, or any other custom template.

Unfortunately that will never happen. All export formats are designed to be write-only as it allows us to avoid a ton of otherwise inevitable complexity. Even JSON, which is the most stable format, does not retain enough data to re-generate an export in, say, HTML. Ultimately, if you want to have exports in two different formats, you will have to export your logs in two different formats.

You linked a few issues in your post, but I don't see how they're related.

- #743 is related to minifying the HTML output, which has nothing to do with regenerating that output from other sources. It would just be applied as a change to all HTML exports.
- #345 is related to inconsistent whitespace handling in the templates, which will be indirectly solved by #743.
- #265 is about adding an option to export in multiple formats _at once_. This will most likely be supported eventually, but this won't solve your "gigabytes of duplicate data" issue. Still, it's probably your best bet, considering your use cases.
- #262 is about adding a completely different output format. Unlikely to happen, but still unrelated to the whole regeneration issue.

In any case, anything related to opening existing exports is out of scope for the project. I recommend looking into #265 as it's closest to solving your issues.

> The logic around message grouping and referencing previous messages, and even images is not important to me -- just basic display of text chat with timestamps within the existing HTML style would be sufficient.

Not to you, but it may be important to others. We can't implement changes based on individual use cases.

> There may be existing 3rd party tools which could achieve this - some instructions on the wiki would really help.

If you find it, you are welcome to update the wiki to help others after you.

**Comment by anomaly33k** [comment]
Thank you ☺️

**Comment by sus-impost0r** [comment]
@anomaly33k Try [jq](https://github.com/stedolan/jq)! An example to process messages into a human-readable format might be:
```
jq -r '.messages[] | .author.nickname + " (" + .author.name + "#" + .author.discriminator + ") => " + .content + "\n"'
```
