### ISSUE TITLE
File owner issue resulting from Docker export - always as root

### ISSUE THREAD

**Issue by KarelWintersky** [Tyrrrz/DiscordChatExporter#800]
### Version

latest

### Flavor

CLI (Command Line Interface)

### Export format

HTML, TXT, JSON, CSV

### Details

All exported files have `root:root` permissions. Docker started from user.

```
arris@blacktower:~$ docker run --rm -v /home/arris/out/:/app/out tyrrrz/discordchatexporter:latest export -t TOKEN -c ID -f json
Exporting 1 channel(s)...
Форпост Тейндар / ryan_sutherland: 0%
Форпост Тейндар / ryan_sutherland: 50%
Форпост Тейндар / ryan_sutherland: 79%
Форпост Тейндар / ryan_sutherland: 97%
Successfully exported 1 channel(s).
arris@blacktower:~$ ls -la /home/arris/out/
total 4044
drwxr-xr-x 2 root  root     4096 Feb  4 23:24  .
drwxr-xr-x 9 arris arris    4096 Feb  4 23:24  ..
-rw-r--r-- 1 root  root  4131820 Feb  4 23:24 'Мир Источника - Форпост Тейндар - ryan_sutherland [574348906230448138].json'
```

Docker image built from source, as recommended here: 
https://github.com/Tyrrrz/DiscordChatExporter/wiki/Docker-usage-instructions 

P.S. Possible duplicate of #401 closed by user, but have unresolved same issue

### Steps to reproduce

- Build docker image
- Run export
- ...
- WTF?

**Comment by Tyrrrz** [comment]
@evangelos-ch do you remember how you were able to solve it in #401?

**Comment by evangelos-ch** [comment]
Here's what I do:

1. Run the DiscordChatExporter via Docker with the `--user "$uid:$gid"` option where `$uid` and `$gid` are my linux user's user id and group id. This is a docker-level CLI option for reference just like volume (`-v`).
2. I don't map a volume to `/app/out` I map a volume to a directory inside that. So I've got a volume like `/path/to/archives:/app/out/archives` and then I use the DiscordChatExporter `-o` option to set the export to be inside that directory manually, so it's something like `-o archives/$channelid.html` (I export as html in your case it'd prob be `-o archives/$channelid.json`

From what I can see there is no `USER` command in the Dockerfile for DiscordChatExporter and this is fine but it means that everything will run as root unless you [run the Docker daemon in rootless mode](https://docs.docker.com/engine/security/rootless/). That is a tricky setup though and 99% of Docker users (myself included) have installed it in root mode, so we need to set the user manually with the `--user` / `-u` option.

Then I think if the folder you are trying to mount (`/home/arris/out` in @KarelWintersky 's case) exists and already has non-root permissions you should be good to go. But if it doesn't already exist (like in my deployment use case for DiscordChatExporter) then since `/app/out` gets created at the image creation time (before the `--user` flag has time to take effect) and everything in the Dockerfile is run as root, so... the automatically created volume folder on your PC will also have root permissions regardless of if you use the `--user` option. Which is why I had to do the workaround with sending things to a folder *inside* `/app/out` that will have to get created during the image runtime and not the image creation, and then it works.

**Comment by Tyrrrz** [comment]
Thank you @evangelos-ch, added a link to this comment to the wiki.
I'm not well versed in Linux systems, so if anyone wants to contribute a PR to amend the Dockerfile to work properly without additional steps I'd be happy. 🙂

**Comment by KarelWintersky** [comment]
```
arris@blacktower:~$ docker run --rm -v /home/arris/out/:/app/out tyrrrz/discordchatexporter:latest export -t ... -c ... -f json --user 1000:1000
Unrecognized option(s):
--user
```
O.O

**Comment by KarelWintersky** [comment]
```
arris@blacktower:~$ docker run --rm --user 1000:1000 -v /home/arris/out/:/app/out tyrrrz/discordchatexporter:latest export -t TOKEN -c CHANNEL -f json
Exporting 1 channel(s)...
Форпост Тейндар / ryan_sutherland: 0%
ERROR
System.UnauthorizedAccessException: Access to the path '/app/out/Мир Источника - Форпост Тейндар - ryan_sutherland [574348906230448138].json' is denied.
    System.IO.IOException: Permission denied
```

**Comment by Tyrrrz** [comment]
@KarelWintersky try passing a subdirectory, i.e. `-v /home/arris/out/:/app/out/archives` to Docker CLI and then also passing `-o archives/` to DCE

**Comment by KarelWintersky** [comment]
```
arris@blacktower:~$ docker run --rm --user 1000:1000 -v /home/arris/out/:/app/out/archives/ tyrrrz/discordchatexporter:latest export -t TOKEN -c CHANNEL -f json -o archives/

Exporting 1 channel(s)...
Форпост Тейндар / ryan_sutherland: 0%
ERROR
System.UnauthorizedAccessException: Access to the path '/app/out/archives/Мир Источника - Форпост Тейндар - ryan_sutherland [574348906230448138].json' is denied.
```
Nope :(

I think, it is a docker issue, not a DCE issue...

**Comment by KarelWintersky** [comment]
So, Docker ignores option `--user 1000:1000`  - directory created with root:root ALWAYS.

**Comment by KarelWintersky** [comment]
I think, best way is:

```
 EXPORT_PATH=/path/to/ && mkdir -p ${EXPORT_PATH} && docker run --rm --user $(id -u):$(id -g) -v ${EXPORT_PATH}:/app/out/ tyrrrz/discordchatexporter:latest <command><options>
```
@Tyrrrz , update README and WIKI please ;-)
