### ISSUE TITLE
Always get stuck in the same message when exporting

### ISSUE THREAD

**Issue by SLOBAX** [Tyrrrz/DiscordChatExporter#82]
First of all thank you for this amazing software, but for the last few days i have problems trying to export a specific channel.

Whenever I try to export that particular chat, it always export the same number of messages.

However if I try to export any other chat it works perfectly and it exports until the last message.

I do not know what the problem may be, any ideas?

Thanks in advance

**Comment by Tyrrrz** [comment]
Hi.
What exactly do you mean by stuck?

**Comment by SLOBAX** [comment]
Sorry, English is not my language.

I mean that no matter how many messages that chat has, it always exports the first 4500, but not the rest, but only happens with that chat.

If I try it with any other chat it exports all the messages from the first to the last one.

**Comment by Tyrrrz** [comment]
Hm...
That's really weird. Is it a public channel somewhere?

**Comment by SLOBAX** [comment]
No, it's a private channel.
Could it be the problem that there is another channel with the same name plus an extension?

For example:

private
private-offtopic

If I'm not mistaken, the problem started happening after that second channel was created, although it could be a coincidence.

**Comment by Tyrrrz** [comment]
No, the name doesn't have anything to do with it.
I don't know of anything that could cause this problem.

**Comment by SLOBAX** [comment]
Is there any way to get a software log to see if you see something weird?

Maybe that will help you.

**Comment by Tyrrrz** [comment]
No, there are no logs.
Is there anything special about that last message? Can you screenshot it in Discord?

**Comment by Tyrrrz** [comment]
There is message count at the top of the exported log, does it show 4500 or the full number of messages?

**Comment by SLOBAX** [comment]
I tried both ways, with and without date setting, but none worked.

Wow, with version 2.4.1 works perfect.

**Comment by Tyrrrz** [comment]
Okay so I guess I have an idea what's causing it but not sure why. It would help if this could be replicated on some public channel...

**Comment by SLOBAX** [comment]
It only happens on that channel and I'm not the admin, I can not put you in it to do tests.

The only thing I can do is if you release an update try it on that same channel and checks if it works.

**Comment by Tyrrrz** [comment]
@SLOBAX is this issue still relevant?
Has anyone else been able to reproduce this?

**Comment by SLOBAX** [comment]
Sorry, I did not realize you had updated the software, i was using 2.4.1 cli. 

I just tried version 2.7 and it works fine.

**Comment by youngcharacter** [comment]
Sorry if this bug is already closed, I'm newish to GitHub, but I think I have the same issue. 

I can't see the last messages that I sent in certain DMs. Some export fine and include all recent messages while a few stopped "updating" some days ago. They seem to have stopped _updating_ when a group was created with me and one of the people in it, but that's just some speculation on what it could be. Could it be something to do with my auth token? 

This is happening with the 2.7.0.0 release.

**Comment by Tyrrrz** [comment]
@SLOBAX good to hear
@youngcharacter can you give a little bit more info? What is the last message it parses and what is the message it gets stuck on? Is it always stuck on the same message? Does the situation change if there are new messages added?

**Comment by youngcharacter** [comment]
I'm sorry for the late response, but the issue seems to have fixed itself. I don't know if it was something to do with my token or something, but waiting around a day or two seems to have fixed it.

- The last messages weren't anything special, just some plain-text messages.
- It happened with multiple chats. Unfortunately, I don't think I tested with group DMs.
- It always got stuck on the same messages and would not update with newer messages.
- New messages popped up, and I could still see if I joined a group, but chats that were already present would not update with any newer messages that were sent after the problem started happening.

I'm sorry if I'm not being very clear. I'll try to respond a little sooner if there is anything more that you need.

**Comment by Tyrrrz** [comment]
@youngcharacter just to make sure, what version are you using?

**Comment by youngcharacter** [comment]
@Tyrrrz I'm using 2.7.0.0.

**Comment by Tyrrrz** [comment]
Ok I'll close this for now. If the problem repeats itself, please re-open this issue.
