### ISSUE TITLE
Make group chat name changes/user kick messages in line with discord

### ISSUE THREAD

**Issue by Tangytube** [Tyrrrz/DiscordChatExporter#844]
### Details

How it should look

![image](https://user-images.githubusercontent.com/71666730/166857127-49674edf-a830-4a08-95e1-ba0afbd7a875.png)

How it looks currently

![image](https://user-images.githubusercontent.com/71666730/166857132-22ede40d-8259-4a88-abbd-142477d464a7.png)
![image](https://user-images.githubusercontent.com/71666730/166859361-8b6c6c05-d4bc-4f67-930b-4d9997218cda.png)

The messages should definitely more descriptive, or if possible completely faithful to discord's ui. Currently the "Changed the channel name" message doesnt show what the name was changed to, and the join/leave messages dont show who left or joined, only the person who added/kicked someone. As for the pinned messages in txt format, maybe there could be some sort of text indicator in the message that it was pinned?

Only included this in the screenshot because i wasnt sure if this was just a fluke or not, but shouldnt the "Pinned a message" reply show the message that was pinned? Not sure why it says it was deleted/couldnt be loaded.

**Comment by gan-of-culture** [comment]
Pin and join messages have been updated with #926. The other system messages can be added quite easily now if needed.

**Comment by CanePlayz** [comment]
Here's a comparison between Discord and the current DCE version:

Discord client:

![image](https://user-images.githubusercontent.com/81419612/213452008-f41aba18-118a-442c-bb95-0c8d278874ad.png)

DCE:

![image](https://user-images.githubusercontent.com/81419612/213451939-c750ca8b-e5dc-4c70-a5d8-aedb11d66266.png)

Here are the things I noticed:

- Missing arrows when someone gets added to the group, gets kicked from the group or leaves the group.
- Missing pen icon when changing group name or icon.
- Missing names of people who joined/left.
- Missing new name of the group.

(@gan-of-culture just tagging you since you've worked on this in the past)
