### ISSUE TITLE
Attempted to export multiple channels, but the output path is neither a directory nor a template

### ISSUE THREAD

**Issue by 0x2b3bfa0** [Tyrrrz/DiscordChatExporter#929]
### Version

2.35.2

### Flavor

CLI (Command Line Interface)

### Details

Same issue as #917.

Can be solved by either
* running `mkdir --parents {path}` first, where `{path}` is the `--output` directory, or
* adding a trailing slash to the `--output` directory path, as suggested in [#917 (comment)](https://github.com/Tyrrrz/DiscordChatExporter/issues/917#issuecomment-1233283878)

### Steps to reproduce

```bash
docker run --rm --volume "$PWD:/output" \
tyrrrz/discordchatexporter:2.35.2 exportguild \
--output /output/data/Json \
--format Json \
--guild ... \
--token ...
```

```console
Fetching channels...
Attempted to export multiple channels, but the output path is neither a directory nor a template.
```

**Comment by 0x2b3bfa0** [comment]
Reopening because it doesn't seem to be fixed on the latest version, as hinted in https://github.com/Tyrrrz/DiscordChatExporter/issues/917#issuecomment-1236362174

**Comment by Tyrrrz** [comment]
This is, in fact, as intended because you supplied an output path which is ambiguous, and it's treated as a file path without extension. In the previous versions (before this error was introduced) this would result in all channels being overwritten into one file. What the linked fix did was resolve situations where the path is ambiguous but points to an _existing_ directory – which removes the ambiguity.

The correct solution here is to append a slash at the end of the path. I will extend the error message to make it clear.

**Comment by Tyrrrz** [comment]
Also, if you are curious why ambiguous paths fall back to file paths – it's because file paths without extensions are valid. If DCE assumed that such paths are meant to be treated as directories, there wouldn't be a way to specify an extension-less file path. On the other hand, if we fall back to treating it as a file, the user has the option to remove the ambiguity by adding a slash.

I know that using file paths without extensions is not very common, but there's value in being explicit. For example, if the user accidentally forgot the extension while actually intending to export into a single file, this error would prevent them from making that mistake early in the process.

**Comment by 0x2b3bfa0** [comment]
Thank you very much!
