### ISSUE TITLE
Discord token not changing

### ISSUE THREAD

**Issue by tcepsa123** [Tyrrrz/DiscordChatExporter#96]
My friend and I have been trolling some of my other friends by using each others account via our tokens. However, whenever we go to the Local Storage place in inspect element, and we change our token and refresh, it no longer works. Was this against TOS and discord fixed it? Or just a bug?

**Comment by RenanYudi** [comment]
Well… Yes… You can no loger use Tokens to login. They probably removed it to mitigate account invasion. 

Not sure if it’s against TOS, since they don’t specify it clearly, but it may fall under “inappropriate user behavior” and your country’s laws if you’re using this for “not so proper things”. 

But that’s not related to this project at all.

**Comment by Tyrrrz** [comment]
I also didn't understand the situation behind the question

**Comment by RenanYudi** [comment]
Nah… It just doesn't work anymore. Email + Password is now the only way of logging in that I current know.
